ALTER TYPE shipment_status ADD VALUE IF NOT EXISTS 'ASIGNADO' AFTER 'PREPARANDO';
ALTER TYPE shipment_status ADD VALUE IF NOT EXISTS 'PENDIENTE_RECEPCION' BEFORE 'ENTREGADO';

ALTER TYPE shipment_event_type ADD VALUE IF NOT EXISTS 'ASIGNACION' AFTER 'CREADO';
ALTER TYPE shipment_event_type ADD VALUE IF NOT EXISTS 'ACEPTACION' AFTER 'ASIGNACION';
ALTER TYPE shipment_event_type ADD VALUE IF NOT EXISTS 'ARRIBO' BEFORE 'ENTREGA';
